### ISSUE TITLE
Cannot find objcgen on MacOS after building Visual Studio Xamarin.ios class lib with NuGet Embedinnator-4000 (.NET Embedding)

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#763]
### Steps to Reproduce

follow instructions at [https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/install/install](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/install/install)

1. Install Visual Studio 2019 Pro onto MacOS
2. Create Xamarin.ios class library project
3. Install Nuget Embeddinator-4000
4. Build project.  It built okay.
5. Open a MacOS Terminal 
6.    Change directory to solution root.

### Expected Behavior
Should find tools :
    ./packages/Embeddinator-4000.[VERSION]/tools/objcgen (Objective-C)
    ./packages/Embeddinator-4000.[VERSION]/tools/Embeddinator-4000.exe

### Actual Behavior
Can't find packages/ or objcgen or Embeddinator-4000.exe

### Environment
MAC OS

```
```

**Comment by chamons** [comment]
```Open a MacOS Terminal
Change directory to solution root.```

Can you post the actual commands you typed, and the output.

**Comment by dbell-movano** [comment]
Very simple:  
1. In Visual Studio 2019 I clicked new > project > xamarin.ios class library
2. I right-clicked project > Nuget manager
3. I browsed Nuget manager for "embeddinator-4000" and clicked INSTALL
4. In Visual Studio I pressed <F5> which builds.

So problem seems most likely that Nuget Emb-4000 installation did not install objcgen.
When I use MacOS Finder and search entire disk for objcgen, it finds nothing.

So, I just changed TITLE of this issue to this:
"Cannot find objcgen on MacOS after installation of NuGet Embedinnator-4000 for Visual Studio Xamarin.ios class lib project"

**Comment by chamons** [comment]
Are you building from VS Windows or VS Mac?

**Comment by dbell-movano** [comment]
VS MAC



————————————————
Douglas K. Bell, VP of Software
MOVANO, Inc.
6200 Stoneridge Mall Rd. Suite 300
Pleasanton, California 94588
(925)200-3200 Tel/Text

On Mar 11, 2020, at 12:43 PM, Chris Hamons <notifications@github.com> wrote:

﻿

Are you building from VS Windows or VS Mac?

**Comment by chamons** [comment]
Oh I bet I know what's going on.

Newer VSfM are likely using PackagesReferences and we haven't updated our documentation. Those explode nugets in a global location, not project specific. 

Check for this path:

 ~/.nuget/packages/embeddinator-4000/0.4.0/tools/objcgen

**Comment by dbell-movano** [comment]
Sorry, my mistake was not first building Embeddinator 4000 project.



————————————————
Douglas K. Bell, VP of Software
MOVANO, Inc.
6200 Stoneridge Mall Rd. Suite 300
Pleasanton, California 94588
(925)200-3200 Tel/Text

On Mar 11, 2020, at 10:24 AM, Chris Hamons <notifications@github.com> wrote:

﻿

Change directory to solution root.```

Can you post the actual commands you typed, and the output.

**Comment by chamons** [comment]
@dbell-movano Does that mean your issue is resolved?

**Comment by dbell-movano** [comment]
No, because emb 4000 gets build errors.



————————————————
Douglas K. Bell, VP of Software
MOVANO, Inc.
6200 Stoneridge Mall Rd. Suite 300
Pleasanton, California 94588
(925)200-3200 Tel/Text

On Mar 11, 2020, at 1:17 PM, Chris Hamons <notifications@github.com> wrote:

﻿

@dbell-movano<https://github.com/dbell-movano> Does that mean your issue is resolved?

**Comment by chamons** [comment]
As noted, this issue still is need-info, and people won't be able to look into it without more details. It is unclear what the issue here is at all:

- Are you unable to find objcgen in the new location?
- Is there a build error? If so what is the command line invocation and full build log?

**Comment by chamons** [comment]
You've now opened 3 issues on this, and none of them are bugs. Closing for https://github.com/mono/Embeddinator-4000/issues/768
